#!/usr/bin/env python3
"""
Export ODETripodPolicy actor to C headers for Teensy (prototype).

Tier A (constants): hyperparameters as #defines; optional nominal open-loop scalars from obs=0, t=0.
Tier B path: same headers include float32 weight/bias arrays for the small actor MLP (no critic).

Does not export value network (not needed for deterministic deploy).

Usage:
  cd e90_repo
  python scripts/export_ode_tripod_teensy.py --checkpoint path/to/model.zip --output-dir teensy_export
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import torch
import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from stable_baselines3 import PPO

from models.ode_gait import ODETripodPolicy  # noqa: F401 — register for load


def _fmt_float_list(arr: np.ndarray, per_line: int = 8) -> str:
    flat = arr.astype(np.float32).flatten(order="C")
    lines = []
    row = []
    for i, x in enumerate(flat):
        row.append(f"{float(x):.8f}f")
        if len(row) >= per_line:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    return "\n".join(lines)


def export_hyper_header(policy: ODETripodPolicy, path: Path, obs_dim: int, core_dim: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "/* Auto-generated by scripts/export_ode_tripod_teensy.py — ODE tripod hyperparameters */",
        "#ifndef ODE_TRIPOD_HYPER_H",
        "#define ODE_TRIPOD_HYPER_H",
        "",
        f"#define ODE_TRIPOD_OBS_DIM ({obs_dim})",
        f"#define ODE_TRIPOD_OBS_CORE_DIM ({core_dim})",
        f"#define ODE_TRIPOD_ACTION_DIM (12)",
        f"#define ODE_TRIPOD_FREQ_HZ_MIN ({policy.freq_hz_min:.8f}f)",
        f"#define ODE_TRIPOD_FREQ_HZ_MAX ({policy.freq_hz_max:.8f}f)",
        f"#define ODE_TRIPOD_MAX_AMP_FLEX ({policy.max_amp_flex:.8f}f)",
        f"#define ODE_TRIPOD_MAX_AMP_ABD ({policy.max_amp_abd:.8f}f)",
        f"#define ODE_TRIPOD_FLEX_SIGN ({policy.flex_sign:.8f}f)",
        f"#define ODE_TRIPOD_ABD_SIGN ({policy.abd_sign:.8f}f)",
        f"#define ODE_TRIPOD_RESIDUAL_SCALE ({policy.residual_scale:.8f}f)",
        "#define ODE_TRIPOD_SIM_TIME_LAST (1) /* last observation index is sim time (seconds) */",
        "",
        "#endif",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def export_actor_weights_header(policy: ODETripodPolicy, path: Path) -> None:
    sd = policy.state_dict()
    chunks = []
    chunks.append("/* Auto-generated — ODETripodPolicy actor weights (float32, row-major per Linear weight) */")
    chunks.append("#ifndef ODE_TRIPOD_ACTOR_WEIGHTS_H")
    chunks.append("#define ODE_TRIPOD_ACTOR_WEIGHTS_H")
    chunks.append("")
    chunks.append("#include <stdint.h>")
    chunks.append("")

    def _keep_actor_key(k: str) -> bool:
        if k.startswith("_value_net"):
            return False
        if k == "log_std":
            return True
        return k.startswith("_actor_core") or k.startswith("_param_head") or k.startswith("_residual_head")

    for key, tensor in sd.items():
        if not _keep_actor_key(key):
            continue
        if not isinstance(tensor, torch.Tensor):
            continue
        t = tensor.detach().cpu().float().numpy()
        safe = key.replace(".", "_")
        var = f"ode_tripod_{safe}"
        chunks.append(f"static const uint32_t {var}_len = {t.size}u;")
        chunks.append(f"static const float {var}[{t.size}] = {{")
        chunks.append(_fmt_float_list(t))
        chunks.append("};")
        chunks.append(f"static const int {var}_shape0 = {t.shape[0] if t.ndim >= 1 else 1};")
        chunks.append(f"static const int {var}_shape1 = {t.shape[1] if t.ndim >= 2 else 1};")
        chunks.append("")

    chunks.append("#endif")
    chunks.append("")
    path.write_text("\n".join(chunks), encoding="utf-8")


def export_nominal_simple(policy: ODETripodPolicy, obs_dim: int, path: Path) -> None:
    device = next(policy.parameters()).device
    z = torch.zeros(1, obs_dim, device=device, dtype=torch.float32)
    with torch.no_grad():
        mean = policy.action_mean_from_obs(z).cpu().numpy().flatten()
        h = policy._actor_core(z[..., :-1])
        raw = policy._param_head(h)
        sig = torch.sigmoid(raw[0, 0]).item()
        freq_hz = policy.freq_hz_min + sig * (policy.freq_hz_max - policy.freq_hz_min)
        amp_flex = float((torch.sigmoid(raw[0, 1]) * policy.max_amp_flex).item())
        amp_abd = float((torch.sigmoid(raw[0, 2]) * policy.max_amp_abd).item())

    lines = [
        "/* Nominal outputs at obs=0, sim_time=0 (Tier A open-loop hint) */",
        "#ifndef ODE_TRIPOD_NOMINAL_H",
        "#define ODE_TRIPOD_NOMINAL_H",
        "",
        f"#define ODE_TRIPOD_NOMINAL_FREQ_HZ ({float(freq_hz):.8f}f)",
        f"#define ODE_TRIPOD_NOMINAL_AMP_FLEX ({amp_flex:.8f}f)",
        f"#define ODE_TRIPOD_NOMINAL_AMP_ABD ({amp_abd:.8f}f)",
        "",
        "static const float ODE_TRIPOD_NOMINAL_ACTION_MEAN[12] = {",
    ]
    for i in range(0, 12, 4):
        chunk = ", ".join(f"{float(mean[j]):.8f}f" for j in range(i, min(i + 4, 12)))
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=str, required=True, help="PPO zip with ODETripodPolicy.")
    parser.add_argument(
        "--output-dir",
        type=str,
        default="teensy_export",
        help="Directory for generated headers (default: teensy_export/).",
    )
    parser.add_argument(
        "--config",
        type=str,
        default=None,
        help="Optional YAML to read obs_dim (must match training). If omitted, taken from loaded policy.",
    )
    args = parser.parse_args()

    ck = Path(args.checkpoint)
    if not ck.is_file():
        raise FileNotFoundError(ck)

    out = PROJECT_ROOT / args.output_dir if not Path(args.output_dir).is_absolute() else Path(args.output_dir)

    model = PPO.load(str(ck), device="cpu")
    policy = model.policy
    if not isinstance(policy, ODETripodPolicy):
        raise TypeError(f"Expected ODETripodPolicy, got {type(policy)}")

    obs_dim = int(np.prod(policy.observation_space.shape))
    if args.config:
        cfg_path = Path(args.config)
        if not cfg_path.is_absolute():
            cfg_path = PROJECT_ROOT / cfg_path
        with open(cfg_path, "r", encoding="utf-8") as f:
            _ = yaml.safe_load(f)

    core_dim = obs_dim - 1 if policy.sim_time_in_obs else obs_dim

    export_hyper_header(policy, out / "ode_tripod_hyper.h", obs_dim, core_dim)
    export_actor_weights_header(policy, out / "ode_tripod_actor_weights.h")
    export_nominal_simple(policy, obs_dim, out / "ode_tripod_nominal.h")

    meta = {
        "checkpoint": str(ck),
        "obs_dim": obs_dim,
        "obs_core_dim": core_dim,
        "sim_time_in_obs": policy.sim_time_in_obs,
        "hidden_sizes": list(policy.hidden_sizes),
        "files": [
            "ode_tripod_hyper.h",
            "ode_tripod_actor_weights.h",
            "ode_tripod_nominal.h",
        ],
    }
    (out / "export_meta.yaml").write_text(yaml.dump(meta, default_flow_style=False), encoding="utf-8")
    print(f"Wrote headers under {out.resolve()}")
    print("  - ode_tripod_hyper.h")
    print("  - ode_tripod_actor_weights.h")
    print("  - ode_tripod_nominal.h")
    print("  - export_meta.yaml")


if __name__ == "__main__":
    main()
