#pragma once

/*
 * Generated by sync_gait_params_from_json.py from:
 *   hexapod_brain_roadmap copy/ode_optimization_no_imu/no_imu_optimization_summary.json
 * Re-run after: python3 hexapod_no_imu_optimization.py
 */

static const float OPT_ABD_REST_DEG[6] = { 10.000f, 10.000f, 0.000f, 0.000f, -10.000f, -10.000f };
static const float OPT_FLX_REST_DEG[6] = { 32.000f, 32.000f, 34.000f, 34.000f, 32.000f, 32.000f };
static const float OPT_ABD_AMP_DEG[6] = { 14.000f, 14.000f, 10.000f, 10.000f, 14.000f, 14.000f };
static const float OPT_FLX_AMP_DEG[6] = { 18.000f, 18.000f, 20.000f, 20.000f, 18.000f, 18.000f };
static const float OPT_ABD_SHIFT_DEG[6] = { -0.000f, -0.000f, 0.000f, 0.000f, -0.000f, -0.000f };
static const float OPT_FLX_SHIFT_DEG[6] = { -90.000f, -90.000f, -90.000f, -90.000f, -90.000f, -90.000f };
static const float OPT_FREQUENCY_HZ = 1.800000f;

static const float OPT_LIFT_SWING_DEG_PEAK = 12.000000f;
