#!/usr/bin/env python3
"""Write optimized_gait_params.h from no_imu_optimization_summary.json (repo-relative)."""

from __future__ import annotations

import json
import sys
from pathlib import Path

# Fixed amplitudes (same as hexapod_no_imu_optimization.py DEFAULT_* — not in 25-D vector)
ABD_AMP = [14.0, 14.0, 10.0, 10.0, 14.0, 14.0]
FLX_AMP = [18.0, 18.0, 20.0, 20.0, 18.0, 18.0]


def main() -> None:
    here = Path(__file__).resolve().parent
    repo = here.parent.parent
    default_json = (
        repo
        / "hexapod_brain_roadmap copy"
        / "ode_optimization_no_imu"
        / "no_imu_optimization_summary.json"
    )
    json_path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else default_json
    data = json.loads(json_path.read_text())
    op = data["optimized_parameters"]

    def fmt6(xs: list, nd: int = 3) -> str:
        return ", ".join(f"{float(x):.{nd}f}f" for x in xs)

    lift = float(op.get("lift_swing_deg_peak", 12.0))
    try:
        rel = json_path.relative_to(repo)
    except ValueError:
        rel = json_path
    out = f"""#pragma once

/*
 * Generated by sync_gait_params_from_json.py from:
 *   {rel}
 * Re-run after: python3 hexapod_no_imu_optimization.py
 */

static const float OPT_ABD_REST_DEG[6] = {{ {fmt6(op["abd_rest_deg"])} }};
static const float OPT_FLX_REST_DEG[6] = {{ {fmt6(op["flx_rest_deg"])} }};
static const float OPT_ABD_AMP_DEG[6] = {{ {fmt6(ABD_AMP)} }};
static const float OPT_FLX_AMP_DEG[6] = {{ {fmt6(FLX_AMP)} }};
static const float OPT_ABD_SHIFT_DEG[6] = {{ {fmt6(op["abd_shift_deg"])} }};
static const float OPT_FLX_SHIFT_DEG[6] = {{ {fmt6(op["flx_shift_deg"])} }};
static const float OPT_FREQUENCY_HZ = {float(op["frequency_hz"]):.6f}f;

static const float OPT_LIFT_SWING_DEG_PEAK = {lift:.6f}f;
"""
    dst = here / "optimized_gait_params.h"
    dst.write_text(out)
    print(f"Wrote {dst}")


if __name__ == "__main__":
    main()
